:: This batch file will compile the example design:
::   1) default      Compile the example design
::   2) clean        Remove any temporary files generated by the compiler
:: Usage: build.bat <target>
:: Example: build.bat default

@ECHO OFF
setlocal ENABLEDELAYEDEXPANSION
:: Only 2 arguments expected
if not "%3"=="" goto usage

set "TARGET=default"
if not "%1"=="" set "TARGET=%1"

set "DEVICE=Arria10"
if not "%2"=="" set "DEVICE=%2"

if "%TARGET%" == "default" (

  echo i++ -march=x86-64 image_inversion.cpp -o tutorial-x86.exe
  i++ -march=x86-64 image_inversion.cpp -o tutorial-x86.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo i++ -march=%DEVICE% -ghdl image_inversion.cpp -o tutorial-fpga.exe
  i++ -march=%DEVICE% -ghdl image_inversion.cpp -o tutorial-fpga.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )

 
  echo tutorial-x86.exe
  tutorial-x86.exe
  echo tutorial-fpga.exe
  tutorial-fpga.exe
  goto:eof

) else if "%TARGET%" == "clean" (
  del /s /f /q *.tmp
  del /s /f /q *.exe
  del /s /f /q *.obj
  rmdir /s /q tutorial-fpga.prj 2>nul
  goto:eof
) else (
  goto usage
)

:: Dump the usage if we get unexpected input
:usage
echo Usage: build.bat [target]
echo Targets: default, clean
echo Example: build.bat default
exit /b 2
