#  Copyright (c) 2021 Intel Corporation                                  
#  SPDX-License-Identifier: MIT                                          

set TOP_LEVEL_NAME "tb"
set USER_DEFINED_ELAB_OPTIONS "-suppress 14408 -suppress 16154"
cd top/sim/mentor
source msim_setup.tcl ;# script generated by qsys for setting up simulation
vlog -sv ../../../tb.sv -suppress 14408 ;# compile testbench
ld_debug  ;# compile and elaborate testbench
onfinish {stop}
log -r *
run -all
set failed [expr [coverage attribute -name TESTSTATUS -concise] > 1]
exit -code ${failed}
