:: This batch file will compile the example design:
::   1) default      Compile the example design
::   2) clean        Remove any temporary files generated by the compiler
:: Usage: build.bat <target>
:: Example: build.bat default

@ECHO OFF
setlocal ENABLEDELAYEDEXPANSION
:: Only one argument expected
if not "%2"=="" goto usage

set "TARGET=default"
if not "%1"=="" set "TARGET=%1"

if "%TARGET%" == "default" (
  echo i++ -march=x86-64 tutorial.cpp -o tutorial.exe
  i++ -march=x86-64 tutorial.cpp -o tutorial.exe
  if not %errorlevel% == 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo i++ -march=x86-64 -D DEBUG_AC_INT_WARNING tutorial.cpp -o tutorial-warning.exe
  i++ -march=x86-64 -D DEBUG_AC_INT_WARNING tutorial.cpp -o tutorial-warning.exe
  if not %errorlevel% == 0 (
    echo Error: Compile failed
    exit /b 1
  )
  
  echo i++ -march=x86-64 -D DEBUG_AC_INT_ERROR tutorial.cpp -o tutorial-error.exe
  i++ -march=x86-64 -D DEBUG_AC_INT_ERROR tutorial.cpp -o tutorial-error.exe
  if not %errorlevel% == 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo tutorial.exe
  tutorial.exe
  echo tutorial-warning.exe
  tutorial-warning.exe
  echo tutorial-error.exe
  tutorial-error.exe
  goto:eof

) else if "%TARGET%" == "clean" (
  del /s /f /q *.tmp
  del /s /f /q *.exe
  del /s /f /q *.obj
  rmdir /s /q tutorial-fpga.prj 2>nul
  goto:eof
) else (
  goto usage
)

:: Dump the usage if we get unexpected input
:usage
echo Usage: build.bat [target]
echo Targets: default, clean
echo Example: build.bat default
exit /b 2
