:: This batch file will compile the example design:
::   1) default      Compile the example design
::   2) clean        Remove any temporary files generated by the compiler
:: Usage: build.bat <target>
:: Example: build.bat default

@ECHO OFF

:: Only 2 arguments expected
if not "%3"=="" goto usage

set "TARGET=default"
if not "%1"=="" set "TARGET=%1"

set "DEVICE=Arria10"
if not "%2"=="" set "DEVICE=%2"

if "%TARGET%" == "default" (
  echo i++ -march=%DEVICE% tutorial.cpp -o stall-enable-default.exe
  i++ -march=%DEVICE% tutorial.cpp -o stall-enable-default.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo i++ -DUSE_STALL_ENABLE -march=%DEVICE% tutorial.cpp -o stall-enable-on.exe
  i++ -DUSE_STALL_ENABLE -march=%DEVICE% tutorial.cpp -o stall-enable-on.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo stall-enable-default.exe
  stall-enable-default.exe
  echo stall-enable-on.exe
  stall-enable-on.exe

  goto:eof

) else if "%TARGET%" == "quartus-compile" (
  echo i++ -march=%DEVICE% --quartus-compile tutorial.cpp -o stall-enable-default.exe
  i++ -march=%DEVICE% --quartus-compile tutorial.cpp -o stall-enable-default.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo i++ -DUSE_STALL_ENABLE -march=%DEVICE% --quartus-compile tutorial.cpp -o stall-enable-on.exe
  i++ -DUSE_STALL_ENABLE -march=%DEVICE% --quartus-compile tutorial.cpp -o stall-enable-on.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo stall-enable-default.exe
  stall-enable-default.exe
  echo stall-enable-on.exe
  stall-enable-on.exe
  goto:eof

) else if "%TARGET%" == "clean" (
  del /s /f *.tmp
  del /s /f *.exe
  del /s /f *.obj
  rmdir /s /q stall-enable-default.prj 2>nul
  rmdir /s /q stall-enable-on.prj 2>nul
  goto:eof
) else (
  goto usage
)

:: Dump the usage if we get unexpected input
:usage
echo Usage: build.bat [target]
echo Targets: default, clean
echo Example: build.bat default
exit /b 2
