// tb_mm_interconnect_9.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 21.1 842

`timescale 1 ps / 1 ps
module tb_mm_interconnect_9 (
		input  wire        clock_reset_inst_clock_clk,                                            //                                          clock_reset_inst_clock.clk
		input  wire        mm_host_dpi_bfm_pred_avs_w_fc1_inst_reset_reset_bridge_in_reset_reset, // mm_host_dpi_bfm_pred_avs_w_fc1_inst_reset_reset_bridge_in_reset.reset
		input  wire [17:0] mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_address,                        //                          mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0.address
		output wire        mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_waitrequest,                    //                                                                .waitrequest
		input  wire [0:0]  mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_burstcount,                     //                                                                .burstcount
		input  wire [0:0]  mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_byteenable,                     //                                                                .byteenable
		input  wire        mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_read,                           //                                                                .read
		output wire [7:0]  mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_readdata,                       //                                                                .readdata
		output wire        mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_readdatavalid,                  //                                                                .readdatavalid
		input  wire        mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_write,                          //                                                                .write
		input  wire [7:0]  mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_writedata,                      //                                                                .writedata
		output wire [15:0] pred_inst_avs_w_fc1_address,                                           //                                             pred_inst_avs_w_fc1.address
		output wire        pred_inst_avs_w_fc1_write,                                             //                                                                .write
		output wire        pred_inst_avs_w_fc1_read,                                              //                                                                .read
		input  wire [31:0] pred_inst_avs_w_fc1_readdata,                                          //                                                                .readdata
		output wire [31:0] pred_inst_avs_w_fc1_writedata,                                         //                                                                .writedata
		output wire [3:0]  pred_inst_avs_w_fc1_byteenable                                         //                                                                .byteenable
	);

	wire         mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_waitrequest;   // mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:av_waitrequest -> mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator:uav_waitrequest
	wire   [7:0] mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_readdata;      // mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:av_readdata -> mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator:uav_readdata
	wire         mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_debugaccess;   // mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator:uav_debugaccess -> mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:av_debugaccess
	wire  [17:0] mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_address;       // mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator:uav_address -> mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:av_address
	wire         mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_read;          // mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator:uav_read -> mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:av_read
	wire   [0:0] mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_byteenable;    // mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator:uav_byteenable -> mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:av_byteenable
	wire         mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_readdatavalid; // mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:av_readdatavalid -> mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator:uav_readdatavalid
	wire         mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_lock;          // mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator:uav_lock -> mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:av_lock
	wire         mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_write;         // mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator:uav_write -> mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:av_write
	wire   [7:0] mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_writedata;     // mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator:uav_writedata -> mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:av_writedata
	wire   [0:0] mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_burstcount;    // mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator:uav_burstcount -> mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:av_burstcount
	wire         rsp_mux_src_valid;                                                                         // rsp_mux:src_valid -> mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:rp_valid
	wire  [60:0] rsp_mux_src_data;                                                                          // rsp_mux:src_data -> mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:rp_data
	wire         rsp_mux_src_ready;                                                                         // mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:rp_ready -> rsp_mux:src_ready
	wire   [0:0] rsp_mux_src_channel;                                                                       // rsp_mux:src_channel -> mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:rp_channel
	wire         rsp_mux_src_startofpacket;                                                                 // rsp_mux:src_startofpacket -> mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:rp_startofpacket
	wire         rsp_mux_src_endofpacket;                                                                   // rsp_mux:src_endofpacket -> mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:rp_endofpacket
	wire  [31:0] pred_inst_avs_w_fc1_agent_m0_readdata;                                                     // pred_inst_avs_w_fc1_translator:uav_readdata -> pred_inst_avs_w_fc1_agent:m0_readdata
	wire         pred_inst_avs_w_fc1_agent_m0_waitrequest;                                                  // pred_inst_avs_w_fc1_translator:uav_waitrequest -> pred_inst_avs_w_fc1_agent:m0_waitrequest
	wire         pred_inst_avs_w_fc1_agent_m0_debugaccess;                                                  // pred_inst_avs_w_fc1_agent:m0_debugaccess -> pred_inst_avs_w_fc1_translator:uav_debugaccess
	wire  [17:0] pred_inst_avs_w_fc1_agent_m0_address;                                                      // pred_inst_avs_w_fc1_agent:m0_address -> pred_inst_avs_w_fc1_translator:uav_address
	wire   [3:0] pred_inst_avs_w_fc1_agent_m0_byteenable;                                                   // pred_inst_avs_w_fc1_agent:m0_byteenable -> pred_inst_avs_w_fc1_translator:uav_byteenable
	wire         pred_inst_avs_w_fc1_agent_m0_read;                                                         // pred_inst_avs_w_fc1_agent:m0_read -> pred_inst_avs_w_fc1_translator:uav_read
	wire         pred_inst_avs_w_fc1_agent_m0_readdatavalid;                                                // pred_inst_avs_w_fc1_translator:uav_readdatavalid -> pred_inst_avs_w_fc1_agent:m0_readdatavalid
	wire         pred_inst_avs_w_fc1_agent_m0_lock;                                                         // pred_inst_avs_w_fc1_agent:m0_lock -> pred_inst_avs_w_fc1_translator:uav_lock
	wire  [31:0] pred_inst_avs_w_fc1_agent_m0_writedata;                                                    // pred_inst_avs_w_fc1_agent:m0_writedata -> pred_inst_avs_w_fc1_translator:uav_writedata
	wire         pred_inst_avs_w_fc1_agent_m0_write;                                                        // pred_inst_avs_w_fc1_agent:m0_write -> pred_inst_avs_w_fc1_translator:uav_write
	wire   [2:0] pred_inst_avs_w_fc1_agent_m0_burstcount;                                                   // pred_inst_avs_w_fc1_agent:m0_burstcount -> pred_inst_avs_w_fc1_translator:uav_burstcount
	wire         pred_inst_avs_w_fc1_agent_rf_source_valid;                                                 // pred_inst_avs_w_fc1_agent:rf_source_valid -> pred_inst_avs_w_fc1_agent_rsp_fifo:in_valid
	wire  [88:0] pred_inst_avs_w_fc1_agent_rf_source_data;                                                  // pred_inst_avs_w_fc1_agent:rf_source_data -> pred_inst_avs_w_fc1_agent_rsp_fifo:in_data
	wire         pred_inst_avs_w_fc1_agent_rf_source_ready;                                                 // pred_inst_avs_w_fc1_agent_rsp_fifo:in_ready -> pred_inst_avs_w_fc1_agent:rf_source_ready
	wire         pred_inst_avs_w_fc1_agent_rf_source_startofpacket;                                         // pred_inst_avs_w_fc1_agent:rf_source_startofpacket -> pred_inst_avs_w_fc1_agent_rsp_fifo:in_startofpacket
	wire         pred_inst_avs_w_fc1_agent_rf_source_endofpacket;                                           // pred_inst_avs_w_fc1_agent:rf_source_endofpacket -> pred_inst_avs_w_fc1_agent_rsp_fifo:in_endofpacket
	wire         pred_inst_avs_w_fc1_agent_rsp_fifo_out_valid;                                              // pred_inst_avs_w_fc1_agent_rsp_fifo:out_valid -> pred_inst_avs_w_fc1_agent:rf_sink_valid
	wire  [88:0] pred_inst_avs_w_fc1_agent_rsp_fifo_out_data;                                               // pred_inst_avs_w_fc1_agent_rsp_fifo:out_data -> pred_inst_avs_w_fc1_agent:rf_sink_data
	wire         pred_inst_avs_w_fc1_agent_rsp_fifo_out_ready;                                              // pred_inst_avs_w_fc1_agent:rf_sink_ready -> pred_inst_avs_w_fc1_agent_rsp_fifo:out_ready
	wire         pred_inst_avs_w_fc1_agent_rsp_fifo_out_startofpacket;                                      // pred_inst_avs_w_fc1_agent_rsp_fifo:out_startofpacket -> pred_inst_avs_w_fc1_agent:rf_sink_startofpacket
	wire         pred_inst_avs_w_fc1_agent_rsp_fifo_out_endofpacket;                                        // pred_inst_avs_w_fc1_agent_rsp_fifo:out_endofpacket -> pred_inst_avs_w_fc1_agent:rf_sink_endofpacket
	wire         mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent_cp_valid;                                     // mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:cp_valid -> router:sink_valid
	wire  [60:0] mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent_cp_data;                                      // mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:cp_data -> router:sink_data
	wire         mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent_cp_ready;                                     // router:sink_ready -> mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:cp_ready
	wire         mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent_cp_startofpacket;                             // mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:cp_startofpacket -> router:sink_startofpacket
	wire         mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent_cp_endofpacket;                               // mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent:cp_endofpacket -> router:sink_endofpacket
	wire         router_src_valid;                                                                          // router:src_valid -> cmd_demux:sink_valid
	wire  [60:0] router_src_data;                                                                           // router:src_data -> cmd_demux:sink_data
	wire         router_src_ready;                                                                          // cmd_demux:sink_ready -> router:src_ready
	wire   [0:0] router_src_channel;                                                                        // router:src_channel -> cmd_demux:sink_channel
	wire         router_src_startofpacket;                                                                  // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire         router_src_endofpacket;                                                                    // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire         pred_inst_avs_w_fc1_agent_rp_valid;                                                        // pred_inst_avs_w_fc1_agent:rp_valid -> router_001:sink_valid
	wire  [87:0] pred_inst_avs_w_fc1_agent_rp_data;                                                         // pred_inst_avs_w_fc1_agent:rp_data -> router_001:sink_data
	wire         pred_inst_avs_w_fc1_agent_rp_ready;                                                        // router_001:sink_ready -> pred_inst_avs_w_fc1_agent:rp_ready
	wire         pred_inst_avs_w_fc1_agent_rp_startofpacket;                                                // pred_inst_avs_w_fc1_agent:rp_startofpacket -> router_001:sink_startofpacket
	wire         pred_inst_avs_w_fc1_agent_rp_endofpacket;                                                  // pred_inst_avs_w_fc1_agent:rp_endofpacket -> router_001:sink_endofpacket
	wire         cmd_demux_src0_valid;                                                                      // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire  [60:0] cmd_demux_src0_data;                                                                       // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire         cmd_demux_src0_ready;                                                                      // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire   [0:0] cmd_demux_src0_channel;                                                                    // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire         cmd_demux_src0_startofpacket;                                                              // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire         cmd_demux_src0_endofpacket;                                                                // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire         rsp_demux_src0_valid;                                                                      // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire  [60:0] rsp_demux_src0_data;                                                                       // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire         rsp_demux_src0_ready;                                                                      // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire   [0:0] rsp_demux_src0_channel;                                                                    // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire         rsp_demux_src0_startofpacket;                                                              // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire         rsp_demux_src0_endofpacket;                                                                // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket
	wire         cmd_mux_src_valid;                                                                         // cmd_mux:src_valid -> pred_inst_avs_w_fc1_cmd_width_adapter:in_valid
	wire  [60:0] cmd_mux_src_data;                                                                          // cmd_mux:src_data -> pred_inst_avs_w_fc1_cmd_width_adapter:in_data
	wire         cmd_mux_src_ready;                                                                         // pred_inst_avs_w_fc1_cmd_width_adapter:in_ready -> cmd_mux:src_ready
	wire   [0:0] cmd_mux_src_channel;                                                                       // cmd_mux:src_channel -> pred_inst_avs_w_fc1_cmd_width_adapter:in_channel
	wire         cmd_mux_src_startofpacket;                                                                 // cmd_mux:src_startofpacket -> pred_inst_avs_w_fc1_cmd_width_adapter:in_startofpacket
	wire         cmd_mux_src_endofpacket;                                                                   // cmd_mux:src_endofpacket -> pred_inst_avs_w_fc1_cmd_width_adapter:in_endofpacket
	wire         pred_inst_avs_w_fc1_cmd_width_adapter_src_valid;                                           // pred_inst_avs_w_fc1_cmd_width_adapter:out_valid -> pred_inst_avs_w_fc1_agent:cp_valid
	wire  [87:0] pred_inst_avs_w_fc1_cmd_width_adapter_src_data;                                            // pred_inst_avs_w_fc1_cmd_width_adapter:out_data -> pred_inst_avs_w_fc1_agent:cp_data
	wire         pred_inst_avs_w_fc1_cmd_width_adapter_src_ready;                                           // pred_inst_avs_w_fc1_agent:cp_ready -> pred_inst_avs_w_fc1_cmd_width_adapter:out_ready
	wire   [0:0] pred_inst_avs_w_fc1_cmd_width_adapter_src_channel;                                         // pred_inst_avs_w_fc1_cmd_width_adapter:out_channel -> pred_inst_avs_w_fc1_agent:cp_channel
	wire         pred_inst_avs_w_fc1_cmd_width_adapter_src_startofpacket;                                   // pred_inst_avs_w_fc1_cmd_width_adapter:out_startofpacket -> pred_inst_avs_w_fc1_agent:cp_startofpacket
	wire         pred_inst_avs_w_fc1_cmd_width_adapter_src_endofpacket;                                     // pred_inst_avs_w_fc1_cmd_width_adapter:out_endofpacket -> pred_inst_avs_w_fc1_agent:cp_endofpacket
	wire         router_001_src_valid;                                                                      // router_001:src_valid -> pred_inst_avs_w_fc1_rsp_width_adapter:in_valid
	wire  [87:0] router_001_src_data;                                                                       // router_001:src_data -> pred_inst_avs_w_fc1_rsp_width_adapter:in_data
	wire         router_001_src_ready;                                                                      // pred_inst_avs_w_fc1_rsp_width_adapter:in_ready -> router_001:src_ready
	wire   [0:0] router_001_src_channel;                                                                    // router_001:src_channel -> pred_inst_avs_w_fc1_rsp_width_adapter:in_channel
	wire         router_001_src_startofpacket;                                                              // router_001:src_startofpacket -> pred_inst_avs_w_fc1_rsp_width_adapter:in_startofpacket
	wire         router_001_src_endofpacket;                                                                // router_001:src_endofpacket -> pred_inst_avs_w_fc1_rsp_width_adapter:in_endofpacket
	wire         pred_inst_avs_w_fc1_rsp_width_adapter_src_valid;                                           // pred_inst_avs_w_fc1_rsp_width_adapter:out_valid -> rsp_demux:sink_valid
	wire  [60:0] pred_inst_avs_w_fc1_rsp_width_adapter_src_data;                                            // pred_inst_avs_w_fc1_rsp_width_adapter:out_data -> rsp_demux:sink_data
	wire         pred_inst_avs_w_fc1_rsp_width_adapter_src_ready;                                           // rsp_demux:sink_ready -> pred_inst_avs_w_fc1_rsp_width_adapter:out_ready
	wire   [0:0] pred_inst_avs_w_fc1_rsp_width_adapter_src_channel;                                         // pred_inst_avs_w_fc1_rsp_width_adapter:out_channel -> rsp_demux:sink_channel
	wire         pred_inst_avs_w_fc1_rsp_width_adapter_src_startofpacket;                                   // pred_inst_avs_w_fc1_rsp_width_adapter:out_startofpacket -> rsp_demux:sink_startofpacket
	wire         pred_inst_avs_w_fc1_rsp_width_adapter_src_endofpacket;                                     // pred_inst_avs_w_fc1_rsp_width_adapter:out_endofpacket -> rsp_demux:sink_endofpacket
	wire         pred_inst_avs_w_fc1_agent_rdata_fifo_src_valid;                                            // pred_inst_avs_w_fc1_agent:rdata_fifo_src_valid -> avalon_st_adapter:in_0_valid
	wire  [33:0] pred_inst_avs_w_fc1_agent_rdata_fifo_src_data;                                             // pred_inst_avs_w_fc1_agent:rdata_fifo_src_data -> avalon_st_adapter:in_0_data
	wire         pred_inst_avs_w_fc1_agent_rdata_fifo_src_ready;                                            // avalon_st_adapter:in_0_ready -> pred_inst_avs_w_fc1_agent:rdata_fifo_src_ready
	wire         avalon_st_adapter_out_0_valid;                                                             // avalon_st_adapter:out_0_valid -> pred_inst_avs_w_fc1_agent:rdata_fifo_sink_valid
	wire  [33:0] avalon_st_adapter_out_0_data;                                                              // avalon_st_adapter:out_0_data -> pred_inst_avs_w_fc1_agent:rdata_fifo_sink_data
	wire         avalon_st_adapter_out_0_ready;                                                             // pred_inst_avs_w_fc1_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire   [0:0] avalon_st_adapter_out_0_error;                                                             // avalon_st_adapter:out_0_error -> pred_inst_avs_w_fc1_agent:rdata_fifo_sink_error

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (18),
		.AV_DATA_W                   (8),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (1),
		.UAV_ADDRESS_W               (18),
		.UAV_BURSTCOUNT_W            (1),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (1),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator (
		.clk                    (clock_reset_inst_clock_clk),                                                                //                       clk.clk
		.reset                  (mm_host_dpi_bfm_pred_avs_w_fc1_inst_reset_reset_bridge_in_reset_reset),                     //                     reset.reset
		.uav_address            (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_burstcount),                                         //                          .burstcount
		.av_byteenable          (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_byteenable),                                         //                          .byteenable
		.av_read                (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_read),                                               //                          .read
		.av_readdata            (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_readdata),                                           //                          .readdata
		.av_readdatavalid       (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_readdatavalid),                                      //                          .readdatavalid
		.av_write               (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_write),                                              //                          .write
		.av_writedata           (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_writedata),                                          //                          .writedata
		.av_beginbursttransfer  (1'b0),                                                                                      //               (terminated)
		.av_begintransfer       (1'b0),                                                                                      //               (terminated)
		.av_chipselect          (1'b0),                                                                                      //               (terminated)
		.av_lock                (1'b0),                                                                                      //               (terminated)
		.av_debugaccess         (1'b0),                                                                                      //               (terminated)
		.uav_clken              (),                                                                                          //               (terminated)
		.av_clken               (1'b1),                                                                                      //               (terminated)
		.uav_response           (2'b00),                                                                                     //               (terminated)
		.av_response            (),                                                                                          //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                                      //               (terminated)
		.av_writeresponsevalid  ()                                                                                           //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (16),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (18),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (3),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) pred_inst_avs_w_fc1_translator (
		.clk                    (clock_reset_inst_clock_clk),                                            //                      clk.clk
		.reset                  (mm_host_dpi_bfm_pred_avs_w_fc1_inst_reset_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (pred_inst_avs_w_fc1_agent_m0_address),                                  // avalon_universal_slave_0.address
		.uav_burstcount         (pred_inst_avs_w_fc1_agent_m0_burstcount),                               //                         .burstcount
		.uav_read               (pred_inst_avs_w_fc1_agent_m0_read),                                     //                         .read
		.uav_write              (pred_inst_avs_w_fc1_agent_m0_write),                                    //                         .write
		.uav_waitrequest        (pred_inst_avs_w_fc1_agent_m0_waitrequest),                              //                         .waitrequest
		.uav_readdatavalid      (pred_inst_avs_w_fc1_agent_m0_readdatavalid),                            //                         .readdatavalid
		.uav_byteenable         (pred_inst_avs_w_fc1_agent_m0_byteenable),                               //                         .byteenable
		.uav_readdata           (pred_inst_avs_w_fc1_agent_m0_readdata),                                 //                         .readdata
		.uav_writedata          (pred_inst_avs_w_fc1_agent_m0_writedata),                                //                         .writedata
		.uav_lock               (pred_inst_avs_w_fc1_agent_m0_lock),                                     //                         .lock
		.uav_debugaccess        (pred_inst_avs_w_fc1_agent_m0_debugaccess),                              //                         .debugaccess
		.av_address             (pred_inst_avs_w_fc1_address),                                           //      avalon_anti_slave_0.address
		.av_write               (pred_inst_avs_w_fc1_write),                                             //                         .write
		.av_read                (pred_inst_avs_w_fc1_read),                                              //                         .read
		.av_readdata            (pred_inst_avs_w_fc1_readdata),                                          //                         .readdata
		.av_writedata           (pred_inst_avs_w_fc1_writedata),                                         //                         .writedata
		.av_byteenable          (pred_inst_avs_w_fc1_byteenable),                                        //                         .byteenable
		.av_begintransfer       (),                                                                      //              (terminated)
		.av_beginbursttransfer  (),                                                                      //              (terminated)
		.av_burstcount          (),                                                                      //              (terminated)
		.av_readdatavalid       (1'b0),                                                                  //              (terminated)
		.av_waitrequest         (1'b0),                                                                  //              (terminated)
		.av_writebyteenable     (),                                                                      //              (terminated)
		.av_lock                (),                                                                      //              (terminated)
		.av_chipselect          (),                                                                      //              (terminated)
		.av_clken               (),                                                                      //              (terminated)
		.uav_clken              (1'b0),                                                                  //              (terminated)
		.av_debugaccess         (),                                                                      //              (terminated)
		.av_outputenable        (),                                                                      //              (terminated)
		.uav_response           (),                                                                      //              (terminated)
		.av_response            (2'b00),                                                                 //              (terminated)
		.uav_writeresponsevalid (),                                                                      //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                   //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (60),
		.PKT_ORI_BURST_SIZE_L      (58),
		.PKT_RESPONSE_STATUS_H     (57),
		.PKT_RESPONSE_STATUS_L     (56),
		.PKT_QOS_H                 (45),
		.PKT_QOS_L                 (45),
		.PKT_DATA_SIDEBAND_H       (43),
		.PKT_DATA_SIDEBAND_L       (43),
		.PKT_ADDR_SIDEBAND_H       (42),
		.PKT_ADDR_SIDEBAND_L       (42),
		.PKT_BURST_TYPE_H          (41),
		.PKT_BURST_TYPE_L          (40),
		.PKT_CACHE_H               (55),
		.PKT_CACHE_L               (52),
		.PKT_THREAD_ID_H           (48),
		.PKT_THREAD_ID_L           (48),
		.PKT_BURST_SIZE_H          (39),
		.PKT_BURST_SIZE_L          (37),
		.PKT_TRANS_EXCLUSIVE       (32),
		.PKT_TRANS_LOCK            (31),
		.PKT_BEGIN_BURST           (44),
		.PKT_PROTECTION_H          (51),
		.PKT_PROTECTION_L          (49),
		.PKT_BURSTWRAP_H           (36),
		.PKT_BURSTWRAP_L           (36),
		.PKT_BYTE_CNT_H            (35),
		.PKT_BYTE_CNT_L            (33),
		.PKT_ADDR_H                (26),
		.PKT_ADDR_L                (9),
		.PKT_TRANS_COMPRESSED_READ (27),
		.PKT_TRANS_POSTED          (28),
		.PKT_TRANS_WRITE           (29),
		.PKT_TRANS_READ            (30),
		.PKT_DATA_H                (7),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (8),
		.PKT_BYTEEN_L              (8),
		.PKT_SRC_ID_H              (46),
		.PKT_SRC_ID_L              (46),
		.PKT_DEST_ID_H             (47),
		.PKT_DEST_ID_L             (47),
		.ST_DATA_W                 (61),
		.ST_CHANNEL_W              (1),
		.AV_BURSTCOUNT_W           (1),
		.SUPPRESS_0_BYTEEN_RSP     (1),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent (
		.clk                   (clock_reset_inst_clock_clk),                                                                //       clk.clk
		.reset                 (mm_host_dpi_bfm_pred_avs_w_fc1_inst_reset_reset_bridge_in_reset_reset),                     // clk_reset.reset
		.av_address            (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent_cp_valid),                                     //        cp.valid
		.cp_data               (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent_cp_data),                                      //          .data
		.cp_startofpacket      (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent_cp_ready),                                     //          .ready
		.rp_valid              (rsp_mux_src_valid),                                                                         //        rp.valid
		.rp_data               (rsp_mux_src_data),                                                                          //          .data
		.rp_channel            (rsp_mux_src_channel),                                                                       //          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                                                 //          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                                                   //          .endofpacket
		.rp_ready              (rsp_mux_src_ready),                                                                         //          .ready
		.av_response           (),                                                                                          // (terminated)
		.av_writeresponsevalid ()                                                                                           // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (87),
		.PKT_ORI_BURST_SIZE_L      (85),
		.PKT_RESPONSE_STATUS_H     (84),
		.PKT_RESPONSE_STATUS_L     (83),
		.PKT_BURST_SIZE_H          (66),
		.PKT_BURST_SIZE_L          (64),
		.PKT_TRANS_LOCK            (58),
		.PKT_BEGIN_BURST           (71),
		.PKT_PROTECTION_H          (78),
		.PKT_PROTECTION_L          (76),
		.PKT_BURSTWRAP_H           (63),
		.PKT_BURSTWRAP_L           (63),
		.PKT_BYTE_CNT_H            (62),
		.PKT_BYTE_CNT_L            (60),
		.PKT_ADDR_H                (53),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (54),
		.PKT_TRANS_POSTED          (55),
		.PKT_TRANS_WRITE           (56),
		.PKT_TRANS_READ            (57),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (73),
		.PKT_SRC_ID_L              (73),
		.PKT_DEST_ID_H             (74),
		.PKT_DEST_ID_L             (74),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (1),
		.ST_DATA_W                 (88),
		.AVS_BURSTCOUNT_W          (3),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) pred_inst_avs_w_fc1_agent (
		.clk                     (clock_reset_inst_clock_clk),                                            //             clk.clk
		.reset                   (mm_host_dpi_bfm_pred_avs_w_fc1_inst_reset_reset_bridge_in_reset_reset), //       clk_reset.reset
		.m0_address              (pred_inst_avs_w_fc1_agent_m0_address),                                  //              m0.address
		.m0_burstcount           (pred_inst_avs_w_fc1_agent_m0_burstcount),                               //                .burstcount
		.m0_byteenable           (pred_inst_avs_w_fc1_agent_m0_byteenable),                               //                .byteenable
		.m0_debugaccess          (pred_inst_avs_w_fc1_agent_m0_debugaccess),                              //                .debugaccess
		.m0_lock                 (pred_inst_avs_w_fc1_agent_m0_lock),                                     //                .lock
		.m0_readdata             (pred_inst_avs_w_fc1_agent_m0_readdata),                                 //                .readdata
		.m0_readdatavalid        (pred_inst_avs_w_fc1_agent_m0_readdatavalid),                            //                .readdatavalid
		.m0_read                 (pred_inst_avs_w_fc1_agent_m0_read),                                     //                .read
		.m0_waitrequest          (pred_inst_avs_w_fc1_agent_m0_waitrequest),                              //                .waitrequest
		.m0_writedata            (pred_inst_avs_w_fc1_agent_m0_writedata),                                //                .writedata
		.m0_write                (pred_inst_avs_w_fc1_agent_m0_write),                                    //                .write
		.rp_endofpacket          (pred_inst_avs_w_fc1_agent_rp_endofpacket),                              //              rp.endofpacket
		.rp_ready                (pred_inst_avs_w_fc1_agent_rp_ready),                                    //                .ready
		.rp_valid                (pred_inst_avs_w_fc1_agent_rp_valid),                                    //                .valid
		.rp_data                 (pred_inst_avs_w_fc1_agent_rp_data),                                     //                .data
		.rp_startofpacket        (pred_inst_avs_w_fc1_agent_rp_startofpacket),                            //                .startofpacket
		.cp_ready                (pred_inst_avs_w_fc1_cmd_width_adapter_src_ready),                       //              cp.ready
		.cp_valid                (pred_inst_avs_w_fc1_cmd_width_adapter_src_valid),                       //                .valid
		.cp_data                 (pred_inst_avs_w_fc1_cmd_width_adapter_src_data),                        //                .data
		.cp_startofpacket        (pred_inst_avs_w_fc1_cmd_width_adapter_src_startofpacket),               //                .startofpacket
		.cp_endofpacket          (pred_inst_avs_w_fc1_cmd_width_adapter_src_endofpacket),                 //                .endofpacket
		.cp_channel              (pred_inst_avs_w_fc1_cmd_width_adapter_src_channel),                     //                .channel
		.rf_sink_ready           (pred_inst_avs_w_fc1_agent_rsp_fifo_out_ready),                          //         rf_sink.ready
		.rf_sink_valid           (pred_inst_avs_w_fc1_agent_rsp_fifo_out_valid),                          //                .valid
		.rf_sink_startofpacket   (pred_inst_avs_w_fc1_agent_rsp_fifo_out_startofpacket),                  //                .startofpacket
		.rf_sink_endofpacket     (pred_inst_avs_w_fc1_agent_rsp_fifo_out_endofpacket),                    //                .endofpacket
		.rf_sink_data            (pred_inst_avs_w_fc1_agent_rsp_fifo_out_data),                           //                .data
		.rf_source_ready         (pred_inst_avs_w_fc1_agent_rf_source_ready),                             //       rf_source.ready
		.rf_source_valid         (pred_inst_avs_w_fc1_agent_rf_source_valid),                             //                .valid
		.rf_source_startofpacket (pred_inst_avs_w_fc1_agent_rf_source_startofpacket),                     //                .startofpacket
		.rf_source_endofpacket   (pred_inst_avs_w_fc1_agent_rf_source_endofpacket),                       //                .endofpacket
		.rf_source_data          (pred_inst_avs_w_fc1_agent_rf_source_data),                              //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                                         // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                                         //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                                          //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                                         //                .error
		.rdata_fifo_src_ready    (pred_inst_avs_w_fc1_agent_rdata_fifo_src_ready),                        //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (pred_inst_avs_w_fc1_agent_rdata_fifo_src_valid),                        //                .valid
		.rdata_fifo_src_data     (pred_inst_avs_w_fc1_agent_rdata_fifo_src_data),                         //                .data
		.m0_response             (2'b00),                                                                 //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                                                   //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (89),
		.FIFO_DEPTH          (4),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) pred_inst_avs_w_fc1_agent_rsp_fifo (
		.clk               (clock_reset_inst_clock_clk),                                            //       clk.clk
		.reset             (mm_host_dpi_bfm_pred_avs_w_fc1_inst_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (pred_inst_avs_w_fc1_agent_rf_source_data),                              //        in.data
		.in_valid          (pred_inst_avs_w_fc1_agent_rf_source_valid),                             //          .valid
		.in_ready          (pred_inst_avs_w_fc1_agent_rf_source_ready),                             //          .ready
		.in_startofpacket  (pred_inst_avs_w_fc1_agent_rf_source_startofpacket),                     //          .startofpacket
		.in_endofpacket    (pred_inst_avs_w_fc1_agent_rf_source_endofpacket),                       //          .endofpacket
		.out_data          (pred_inst_avs_w_fc1_agent_rsp_fifo_out_data),                           //       out.data
		.out_valid         (pred_inst_avs_w_fc1_agent_rsp_fifo_out_valid),                          //          .valid
		.out_ready         (pred_inst_avs_w_fc1_agent_rsp_fifo_out_ready),                          //          .ready
		.out_startofpacket (pred_inst_avs_w_fc1_agent_rsp_fifo_out_startofpacket),                  //          .startofpacket
		.out_endofpacket   (pred_inst_avs_w_fc1_agent_rsp_fifo_out_endofpacket),                    //          .endofpacket
		.csr_address       (2'b00),                                                                 // (terminated)
		.csr_read          (1'b0),                                                                  // (terminated)
		.csr_write         (1'b0),                                                                  // (terminated)
		.csr_readdata      (),                                                                      // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                                  // (terminated)
		.almost_full_data  (),                                                                      // (terminated)
		.almost_empty_data (),                                                                      // (terminated)
		.in_empty          (1'b0),                                                                  // (terminated)
		.out_empty         (),                                                                      // (terminated)
		.in_error          (1'b0),                                                                  // (terminated)
		.out_error         (),                                                                      // (terminated)
		.in_channel        (1'b0),                                                                  // (terminated)
		.out_channel       ()                                                                       // (terminated)
	);

	tb_mm_interconnect_9_router router (
		.sink_ready         (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent_cp_ready),                 //      sink.ready
		.sink_valid         (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent_cp_valid),                 //          .valid
		.sink_data          (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent_cp_data),                  //          .data
		.sink_startofpacket (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent_cp_startofpacket),         //          .startofpacket
		.sink_endofpacket   (mm_host_dpi_bfm_pred_avs_w_fc1_inst_m0_agent_cp_endofpacket),           //          .endofpacket
		.clk                (clock_reset_inst_clock_clk),                                            //       clk.clk
		.reset              (mm_host_dpi_bfm_pred_avs_w_fc1_inst_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_src_ready),                                                      //       src.ready
		.src_valid          (router_src_valid),                                                      //          .valid
		.src_data           (router_src_data),                                                       //          .data
		.src_channel        (router_src_channel),                                                    //          .channel
		.src_startofpacket  (router_src_startofpacket),                                              //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                                                 //          .endofpacket
	);

	tb_mm_interconnect_9_router_001 router_001 (
		.sink_ready         (pred_inst_avs_w_fc1_agent_rp_ready),                                    //      sink.ready
		.sink_valid         (pred_inst_avs_w_fc1_agent_rp_valid),                                    //          .valid
		.sink_data          (pred_inst_avs_w_fc1_agent_rp_data),                                     //          .data
		.sink_startofpacket (pred_inst_avs_w_fc1_agent_rp_startofpacket),                            //          .startofpacket
		.sink_endofpacket   (pred_inst_avs_w_fc1_agent_rp_endofpacket),                              //          .endofpacket
		.clk                (clock_reset_inst_clock_clk),                                            //       clk.clk
		.reset              (mm_host_dpi_bfm_pred_avs_w_fc1_inst_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_001_src_ready),                                                  //       src.ready
		.src_valid          (router_001_src_valid),                                                  //          .valid
		.src_data           (router_001_src_data),                                                   //          .data
		.src_channel        (router_001_src_channel),                                                //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                                          //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                                             //          .endofpacket
	);

	tb_mm_interconnect_9_cmd_demux cmd_demux (
		.clk                (clock_reset_inst_clock_clk),                                            //       clk.clk
		.reset              (mm_host_dpi_bfm_pred_avs_w_fc1_inst_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_src_ready),                                                      //      sink.ready
		.sink_channel       (router_src_channel),                                                    //          .channel
		.sink_data          (router_src_data),                                                       //          .data
		.sink_startofpacket (router_src_startofpacket),                                              //          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                                                //          .endofpacket
		.sink_valid         (router_src_valid),                                                      //          .valid
		.src0_ready         (cmd_demux_src0_ready),                                                  //      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                                                  //          .valid
		.src0_data          (cmd_demux_src0_data),                                                   //          .data
		.src0_channel       (cmd_demux_src0_channel),                                                //          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                                          //          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                                             //          .endofpacket
	);

	tb_mm_interconnect_9_cmd_mux cmd_mux (
		.clk                 (clock_reset_inst_clock_clk),                                            //       clk.clk
		.reset               (mm_host_dpi_bfm_pred_avs_w_fc1_inst_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                                                     //       src.ready
		.src_valid           (cmd_mux_src_valid),                                                     //          .valid
		.src_data            (cmd_mux_src_data),                                                      //          .data
		.src_channel         (cmd_mux_src_channel),                                                   //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                                             //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                                               //          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                                                  //     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                                                  //          .valid
		.sink0_channel       (cmd_demux_src0_channel),                                                //          .channel
		.sink0_data          (cmd_demux_src0_data),                                                   //          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),                                          //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket)                                             //          .endofpacket
	);

	tb_mm_interconnect_9_cmd_demux rsp_demux (
		.clk                (clock_reset_inst_clock_clk),                                            //       clk.clk
		.reset              (mm_host_dpi_bfm_pred_avs_w_fc1_inst_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (pred_inst_avs_w_fc1_rsp_width_adapter_src_ready),                       //      sink.ready
		.sink_channel       (pred_inst_avs_w_fc1_rsp_width_adapter_src_channel),                     //          .channel
		.sink_data          (pred_inst_avs_w_fc1_rsp_width_adapter_src_data),                        //          .data
		.sink_startofpacket (pred_inst_avs_w_fc1_rsp_width_adapter_src_startofpacket),               //          .startofpacket
		.sink_endofpacket   (pred_inst_avs_w_fc1_rsp_width_adapter_src_endofpacket),                 //          .endofpacket
		.sink_valid         (pred_inst_avs_w_fc1_rsp_width_adapter_src_valid),                       //          .valid
		.src0_ready         (rsp_demux_src0_ready),                                                  //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                                                  //          .valid
		.src0_data          (rsp_demux_src0_data),                                                   //          .data
		.src0_channel       (rsp_demux_src0_channel),                                                //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                                          //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                                             //          .endofpacket
	);

	tb_mm_interconnect_9_rsp_mux rsp_mux (
		.clk                 (clock_reset_inst_clock_clk),                                            //       clk.clk
		.reset               (mm_host_dpi_bfm_pred_avs_w_fc1_inst_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                                                     //       src.ready
		.src_valid           (rsp_mux_src_valid),                                                     //          .valid
		.src_data            (rsp_mux_src_data),                                                      //          .data
		.src_channel         (rsp_mux_src_channel),                                                   //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                                             //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                                               //          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                                                  //     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                                                  //          .valid
		.sink0_channel       (rsp_demux_src0_channel),                                                //          .channel
		.sink0_data          (rsp_demux_src0_data),                                                   //          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),                                          //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket)                                             //          .endofpacket
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (26),
		.IN_PKT_ADDR_L                 (9),
		.IN_PKT_DATA_H                 (7),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (8),
		.IN_PKT_BYTEEN_L               (8),
		.IN_PKT_BYTE_CNT_H             (35),
		.IN_PKT_BYTE_CNT_L             (33),
		.IN_PKT_TRANS_COMPRESSED_READ  (27),
		.IN_PKT_TRANS_WRITE            (29),
		.IN_PKT_BURSTWRAP_H            (36),
		.IN_PKT_BURSTWRAP_L            (36),
		.IN_PKT_BURST_SIZE_H           (39),
		.IN_PKT_BURST_SIZE_L           (37),
		.IN_PKT_RESPONSE_STATUS_H      (57),
		.IN_PKT_RESPONSE_STATUS_L      (56),
		.IN_PKT_TRANS_EXCLUSIVE        (32),
		.IN_PKT_BURST_TYPE_H           (41),
		.IN_PKT_BURST_TYPE_L           (40),
		.IN_PKT_ORI_BURST_SIZE_L       (58),
		.IN_PKT_ORI_BURST_SIZE_H       (60),
		.IN_ST_DATA_W                  (61),
		.OUT_PKT_ADDR_H                (53),
		.OUT_PKT_ADDR_L                (36),
		.OUT_PKT_DATA_H                (31),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (35),
		.OUT_PKT_BYTEEN_L              (32),
		.OUT_PKT_BYTE_CNT_H            (62),
		.OUT_PKT_BYTE_CNT_L            (60),
		.OUT_PKT_TRANS_COMPRESSED_READ (54),
		.OUT_PKT_BURST_SIZE_H          (66),
		.OUT_PKT_BURST_SIZE_L          (64),
		.OUT_PKT_RESPONSE_STATUS_H     (84),
		.OUT_PKT_RESPONSE_STATUS_L     (83),
		.OUT_PKT_TRANS_EXCLUSIVE       (59),
		.OUT_PKT_BURST_TYPE_H          (68),
		.OUT_PKT_BURST_TYPE_L          (67),
		.OUT_PKT_ORI_BURST_SIZE_L      (85),
		.OUT_PKT_ORI_BURST_SIZE_H      (87),
		.OUT_ST_DATA_W                 (88),
		.ST_CHANNEL_W                  (1),
		.OPTIMIZE_FOR_RSP              (0),
		.RESPONSE_PATH                 (0),
		.CONSTANT_BURST_SIZE           (1),
		.PACKING                       (1),
		.ENABLE_ADDRESS_ALIGNMENT      (0)
	) pred_inst_avs_w_fc1_cmd_width_adapter (
		.clk                  (clock_reset_inst_clock_clk),                                            //       clk.clk
		.reset                (mm_host_dpi_bfm_pred_avs_w_fc1_inst_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_valid             (cmd_mux_src_valid),                                                     //      sink.valid
		.in_channel           (cmd_mux_src_channel),                                                   //          .channel
		.in_startofpacket     (cmd_mux_src_startofpacket),                                             //          .startofpacket
		.in_endofpacket       (cmd_mux_src_endofpacket),                                               //          .endofpacket
		.in_ready             (cmd_mux_src_ready),                                                     //          .ready
		.in_data              (cmd_mux_src_data),                                                      //          .data
		.out_endofpacket      (pred_inst_avs_w_fc1_cmd_width_adapter_src_endofpacket),                 //       src.endofpacket
		.out_data             (pred_inst_avs_w_fc1_cmd_width_adapter_src_data),                        //          .data
		.out_channel          (pred_inst_avs_w_fc1_cmd_width_adapter_src_channel),                     //          .channel
		.out_valid            (pred_inst_avs_w_fc1_cmd_width_adapter_src_valid),                       //          .valid
		.out_ready            (pred_inst_avs_w_fc1_cmd_width_adapter_src_ready),                       //          .ready
		.out_startofpacket    (pred_inst_avs_w_fc1_cmd_width_adapter_src_startofpacket),               //          .startofpacket
		.in_command_size_data (3'b000)                                                                 // (terminated)
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (53),
		.IN_PKT_ADDR_L                 (36),
		.IN_PKT_DATA_H                 (31),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (35),
		.IN_PKT_BYTEEN_L               (32),
		.IN_PKT_BYTE_CNT_H             (62),
		.IN_PKT_BYTE_CNT_L             (60),
		.IN_PKT_TRANS_COMPRESSED_READ  (54),
		.IN_PKT_TRANS_WRITE            (56),
		.IN_PKT_BURSTWRAP_H            (63),
		.IN_PKT_BURSTWRAP_L            (63),
		.IN_PKT_BURST_SIZE_H           (66),
		.IN_PKT_BURST_SIZE_L           (64),
		.IN_PKT_RESPONSE_STATUS_H      (84),
		.IN_PKT_RESPONSE_STATUS_L      (83),
		.IN_PKT_TRANS_EXCLUSIVE        (59),
		.IN_PKT_BURST_TYPE_H           (68),
		.IN_PKT_BURST_TYPE_L           (67),
		.IN_PKT_ORI_BURST_SIZE_L       (85),
		.IN_PKT_ORI_BURST_SIZE_H       (87),
		.IN_ST_DATA_W                  (88),
		.OUT_PKT_ADDR_H                (26),
		.OUT_PKT_ADDR_L                (9),
		.OUT_PKT_DATA_H                (7),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (8),
		.OUT_PKT_BYTEEN_L              (8),
		.OUT_PKT_BYTE_CNT_H            (35),
		.OUT_PKT_BYTE_CNT_L            (33),
		.OUT_PKT_TRANS_COMPRESSED_READ (27),
		.OUT_PKT_BURST_SIZE_H          (39),
		.OUT_PKT_BURST_SIZE_L          (37),
		.OUT_PKT_RESPONSE_STATUS_H     (57),
		.OUT_PKT_RESPONSE_STATUS_L     (56),
		.OUT_PKT_TRANS_EXCLUSIVE       (32),
		.OUT_PKT_BURST_TYPE_H          (41),
		.OUT_PKT_BURST_TYPE_L          (40),
		.OUT_PKT_ORI_BURST_SIZE_L      (58),
		.OUT_PKT_ORI_BURST_SIZE_H      (60),
		.OUT_ST_DATA_W                 (61),
		.ST_CHANNEL_W                  (1),
		.OPTIMIZE_FOR_RSP              (1),
		.RESPONSE_PATH                 (1),
		.CONSTANT_BURST_SIZE           (1),
		.PACKING                       (1),
		.ENABLE_ADDRESS_ALIGNMENT      (0)
	) pred_inst_avs_w_fc1_rsp_width_adapter (
		.clk                  (clock_reset_inst_clock_clk),                                            //       clk.clk
		.reset                (mm_host_dpi_bfm_pred_avs_w_fc1_inst_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_valid             (router_001_src_valid),                                                  //      sink.valid
		.in_channel           (router_001_src_channel),                                                //          .channel
		.in_startofpacket     (router_001_src_startofpacket),                                          //          .startofpacket
		.in_endofpacket       (router_001_src_endofpacket),                                            //          .endofpacket
		.in_ready             (router_001_src_ready),                                                  //          .ready
		.in_data              (router_001_src_data),                                                   //          .data
		.out_endofpacket      (pred_inst_avs_w_fc1_rsp_width_adapter_src_endofpacket),                 //       src.endofpacket
		.out_data             (pred_inst_avs_w_fc1_rsp_width_adapter_src_data),                        //          .data
		.out_channel          (pred_inst_avs_w_fc1_rsp_width_adapter_src_channel),                     //          .channel
		.out_valid            (pred_inst_avs_w_fc1_rsp_width_adapter_src_valid),                       //          .valid
		.out_ready            (pred_inst_avs_w_fc1_rsp_width_adapter_src_ready),                       //          .ready
		.out_startofpacket    (pred_inst_avs_w_fc1_rsp_width_adapter_src_startofpacket),               //          .startofpacket
		.in_command_size_data (3'b000)                                                                 // (terminated)
	);

	tb_mm_interconnect_0_avalon_st_adapter #(
		.inBitsPerSymbol (34),
		.inUsePackets    (0),
		.inDataWidth     (34),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (34),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (clock_reset_inst_clock_clk),                                            // in_clk_0.clk
		.in_rst_0_reset (mm_host_dpi_bfm_pred_avs_w_fc1_inst_reset_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (pred_inst_avs_w_fc1_agent_rdata_fifo_src_data),                         //     in_0.data
		.in_0_valid     (pred_inst_avs_w_fc1_agent_rdata_fifo_src_valid),                        //         .valid
		.in_0_ready     (pred_inst_avs_w_fc1_agent_rdata_fifo_src_ready),                        //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                                          //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),                                         //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),                                         //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                                          //         .error
	);

endmodule
