:: This batch file will compile the example design:
::   1) default         Compile the example design
::   2) tutorial-x86-64 Emulate the HLS component only
::   3) clean           Remove any temporary files generated by the compiler
:: Usage: build.bat <target>
:: Example: build.bat default 
:: Example: build.bat default Agilex

@ECHO OFF

:: Only 2 arguments expected
if not "%3"=="" goto usage

set "TARGET=default"
if not "%1"=="" set "TARGET=%1"

set "DEVICE=10AS066N3F40E2SG"
if not "%2"=="" set "DEVICE=%2"

set "PD_SYSTEM_QSYS=system.qsys"
set "QUARTUS_PROJECT=SimpleArria10Project.qpf"
set "QUARTUS_REVISION=sort"

if "%TARGET%" == "default" (
  
  cd hls
  echo build.bat %TARGET% %DEVICE%
  build.bat %TARGET% %DEVICE%

  echo cd ..
  cd ..

  echo xcopy hls\tutorial-fpga.prj\components\sort_bus ip\sort_bus /e /s /i /q /y
  xcopy hls\tutorial-fpga.prj\components\sort_bus ip\sort_bus /e /s /i /q /y

  echo qsys-generate --quartus-project=%QUARTUS_PROJECT% --synthesis=verilog %PD_SYSTEM_QSYS% > qsys-generate.log 2>&1
  qsys-generate --quartus-project=%QUARTUS_PROJECT% --synthesis=verilog %PD_SYSTEM_QSYS% > qsys-generate.log 2>&1
  
  echo quartus_sh --flow compile %QUARTUS_PROJECT% -c %QUARTUS_REVISION% > quartus_sh.log 2>&1
  quartus_sh --flow compile %QUARTUS_PROJECT% -c %QUARTUS_REVISION% > quartus_sh.log 2>&1

  goto:eof
) else if "%TARGET%" == "tutorial-x86-64" (
  echo cd hls
  cd hls
  echo build.bat default x86-64
  build.bat default x86-64
  echo cd ..
  cd ..

  goto:eof
) else if "%TARGET%" == "clean" (
  cd hls
  build.bat clean
  cd ..

  rmdir /s /q tmp-clearbox
  rmdir /s /q system
  rmdir /s /q qdb
  rmdir /s /q ip\sort_bus

  rmdir /s /q ip\system\system_clock_in
  rmdir /s /q ip\system\system_master_0
  rmdir /s /q ip\system\system_reset_in

  del output_files\jtag_id.txt
  del output_files\sort.asm.rpt
  del output_files\sort.fit.finalize.rpt
  del output_files\sort.fit.place.rpt
  del output_files\sort.fit.plan.rpt
  del output_files\sort.fit.route.rpt
  del output_files\sort.fit.rpt
  @REM del output_files\sort.fit.summary
  del output_files\sort.flow.rpt
  del output_files\sort.pin
  del output_files\sort.sld
  @REM del output_files\sort.sof
  @REM del output_files\sort.sta.rpt
  @REM del output_files\sort.sta.summary
  del output_files\sort.syn.rpt
  del output_files\sort.syn.smsg
  del output_files\sort.syn.summary

  goto:eof
) else (
  goto usage
)

:: Dump the usage if we get unexpected input
:usage
echo Usage: build.bat [target]
echo Targets: default, tutorial-x86-64, clean
echo Example: build.bat default
exit /b 2
