:: This batch file will compile the example design:
::   1) default      Compile the example design
::   2) clean        Remove any temporary files generated by the compiler
:: Usage: build.bat <target>
:: Example: build.bat default

@ECHO OFF

:: Only 2 arguments expected
if not "%3"=="" goto usage

set "TARGET=default"
if not "%1"=="" set "TARGET=%1"

set "DEVICE=Arria10"
if not "%2"=="" set "DEVICE=%2"

if "%TARGET%" == "default" (
  echo i++ -march=%DEVICE% part_1.cpp -o part_1-default.exe
  i++ -march=%DEVICE% part_1.cpp -o part_1-default.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo i++ -march=%DEVICE% -ffp-contract=fast -ffp-reassociate part_1.cpp -o part_2-flag.exe
  i++ -march=%DEVICE% -ffp-contract=fast -ffp-reassociate part_1.cpp -o part_2-flag.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo i++ -march=%DEVICE% part_3_pragma.cpp -o part_3-pragma.exe
  i++ -march=%DEVICE% part_3_pragma.cpp -o part_3-pragma.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo i++ -march=%DEVICE% part_4_scoped.cpp -o part_4-scoped.exe
  i++ -march=%DEVICE% part_4_scoped.cpp -o part_4-scoped.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo part_1-default.exe
  part_1-default.exe
  echo part_2-flag.exe
  part_2-flag.exe
  echo part_3-pragma.exe
  part_3-pragma.exe
  echo part_4-scoped.exe
  part_4-scoped.exe

  echo Compilation complete. Open the area report and observe the area associated with the four implementations.
  goto:eof

) else if "%TARGET%" == "clean" (
  del /s /f *.tmp
  del /s /f *.exe
  del /s /f *.obj
  rmdir /s /q part_1-default.prj 2>nul
  rmdir /s /q part_2-flag.prj 2>nul
  rmdir /s /q part_3-pragma.prj 2>nul
  rmdir /s /q part_4-scoped.prj 2>nul
  goto:eof
) else (
  goto usage
)

:: Dump the usage if we get unexpected input
:usage
echo Usage: build.bat [target]
echo Targets: default, clean
echo Example: build.bat default
exit /b 2
