:: This batch file will compile the example design:
::   1) default      Compile the example design
::   2) clean        Remove any temporary files generated by the compiler
:: Usage: build.bat <target>
:: Example: build.bat default

@ECHO OFF
:: Only 2 arguments expected
if not "%3"=="" goto usage

set "TARGET=default"
if not "%1"=="" set "TARGET=%1"

set "DEVICE=Arria10"
if not "%2"=="" set "DEVICE=%2"

if "%TARGET%" == "default" (

  echo i++ -march=%DEVICE%  tutorial.cpp -DUSE_CONST -o tutorial-const.exe
  i++ -march=%DEVICE% tutorial.cpp -DUSE_CONST -o tutorial-const.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo i++ -march=%DEVICE% tutorial.cpp -o tutorial-mutable.exe
  i++ -march=%DEVICE% tutorial.cpp -o tutorial-mutable.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo tutorial-const.exe
  tutorial-const.exe
  echo tutorial-mutable.exe
  tutorial-mutable.exe
  goto:eof

) else if "%TARGET%" == "clean" (
  del /s /f *.tmp
  del /s /f *.exe
  del /s /f *.obj
  rmdir /s /q tutorial-const.prj 2>nul
  rmdir /s /q tutorial-mutable.prj 2>nul
  goto:eof
) else (
  goto usage
)

:: Dump the usage if we get unexpected input
:usage
echo Usage: build.bat [target]
echo Targets: default, clean
echo Example: build.bat default
exit /b 2
