:: This batch file will compile the example design:
::   1) default      Compile the example design
::   2) clean        Remove any temporary files generated by the compiler
:: Usage: build.bat <target>
:: Example: build.bat default

@ECHO OFF

:: Only 2 arguments expected
if not "%3"=="" goto usage

set "TARGET=default"
if not "%1"=="" set "TARGET=%1"

set "DEVICE=Arria10"
if not "%2"=="" set "DEVICE=%2"

if "%TARGET%" == "default" (
  echo i++ -march=%DEVICE% part_1_unbalanced.cpp -o part_1_unbalanced.exe -ffp-reassociate -ghdl
  i++ -march=%DEVICE% part_1_unbalanced.cpp -o part_1_unbalanced.exe -ffp-reassociate -ghdl
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo i++ -march=%DEVICE% part_2_balanced.cpp -o part_2_balanced.exe -ffp-reassociate -ghdl
  i++ -march=%DEVICE% part_2_balanced.cpp -o part_2_balanced.exe -ffp-reassociate -ghdl
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo part_1_unbalanced.exe
  part_1_unbalanced
  echo.

  echo part_2_balanced.exe
  part_2_balanced
  echo.

  echo Compilation complete.  Open the README and the report files to learn how to properly balance pipeline latency when using system of tasks.
  goto:eof

) else if "%TARGET%" == "clean" (
  del /s /f *.tmp
  del /s /f *.exe
  del /s /f *.obj
  rmdir /s /q part_1_unbalanced.prj 2>nul
  rmdir /s /q part_2_balanced.prj 2>nul
  goto:eof
) else (
  goto usage
)

:: Dump the usage if we get unexpected input
:usage
echo Usage: build.bat [target]
echo Targets: default, clean
echo Example: build.bat default
exit /b 2
