:: This batch file will compile the example designs: part_1_global_control.cpp
:: 1) default      Compile the example design
:: 2) clean        Remove any temporary files generated by the compiler
:: Usage: build.bat <target>
:: Example: build.bat default

@ECHO OFF

:: Only 2 arguments expected
if not "%3"=="" goto usage

set "TARGET=default"
if not "%1"=="" set "TARGET=%1"

set "DEVICE=Arria10"
if not "%2"=="" set "DEVICE=%2"

if "%TARGET%" == "default" (
  echo i++ -march=%DEVICE% --quartus-compile part_1_global_control.cpp -o default.exe
  i++ -march=%DEVICE% --quartus-compile part_1_global_control.cpp -o default.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )
  echo i++ -march=%DEVICE% --quartus-compile --dsp-mode=prefer-dsp part_1_global_control.cpp -o global_control_prefer_dsp.exe
  i++ -march=%DEVICE% --quartus-compile --dsp-mode=prefer-dsp part_1_global_control.cpp -o global_control_prefer_dsp.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )
  echo i++ -march=%DEVICE% --quartus-compile --dsp-mode=prefer-softlogic part_1_global_control.cpp -o global_control_prefer_softlogic.exe
  i++ -march=%DEVICE% --quartus-compile --dsp-mode=prefer-softlogic part_1_global_control.cpp -o global_control_prefer_softlogic.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )
  echo i++ -march=%DEVICE% --quartus-compile part_2_local_control.cpp -o local_control.exe
  i++ -march=%DEVICE% --quartus-compile part_2_local_control.cpp -o local_control.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo default.exe
  default.exe
  echo global_control_prefer_dsp.exe
  global_control_prefer_dsp.exe
  echo global_control_prefer_softlogic.exe
  global_control_prefer_softlogic.exe
  echo local_control.exe
  local_control.exe

  echo Compilation complete. Open the area report and observe the DSP usage.
  goto:eof

) else if "%TARGET%" == "clean" (
  del /s /f *.tmp
  del /s /f *.exe
  del /s /f *.obj
  rmdir /s /q default.prj 2>nul
  rmdir /s /q global_control_prefer_dsp.prj 2>nul
  rmdir /s /q global_control_prefer_softlogic.prj 2>nul
  rmdir /s /q local_control.prj 2>nul
  goto:eof
) else (
  goto usage
)

:: Dump the usage if we get unexpected input
:usage
echo Usage: build.bat [target]
echo Targets: default, clean
echo Example: build.bat default
exit /b 2
