:: This batch file will compile the example design:
::   1) default      Compile the example design
::   2) clean        Remove any temporary files generated by the compiler
:: Usage: build.bat <target>
:: Example: build.bat default

@ECHO OFF
:: Only 2 arguments expected
if not "%3"=="" goto usage

set "TARGET=default"
if not "%1"=="" set "TARGET=%1"

set "DEVICE=Arria10"
if not "%2"=="" set "DEVICE=%2"

if "%TARGET%" == "default" (
  build 1_cmp_mult_divergent
  build 2_cmp_mult_efficient
) else if "%TARGET%" == "1_cmp_mult_divergent" (

  echo i++ -march=%DEVICE% 1_cmp_mult_divergent.cpp -o 1_cmp_mult_divergent.exe
  i++ -march=%DEVICE% 1_cmp_mult_divergent.cpp -o 1_cmp_mult_divergent.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo 1_cmp_mult_divergent.exe
  1_cmp_mult_divergent.exe
  goto:eof

) else if "%TARGET%" == "2_cmp_mult_efficient" (

  echo i++ -march=%DEVICE% 2_cmp_mult_efficient.cpp -o 2_cmp_mult_efficient.exe
  i++ -march=%DEVICE% 2_cmp_mult_efficient.cpp -o 2_cmp_mult_efficient.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo 2_cmp_mult_efficient.exe
  2_cmp_mult_efficient.exe
  goto:eof

) else if "%TARGET%" == "clean" (
  del /s /f *.tmp
  del /s /f *.exe
  del /s /f *.obj
  rmdir /s /q 1_cmp_mult_divergent.prj 2>nul
  rmdir /s /q 2_cmp_mult_efficient.prj 2>nul
  goto:eof
) else (
  goto usage
)

:: Dump the usage if we get unexpected input
:usage
echo Usage: build.bat [target]
echo Targets: tutorial-fpga, tutorial-fpga-divergent, clean
echo Example: build.bat tutorial-fpga
exit /b 2
