:: This batch file will compile the example design:
::   1) default      Compile the example design
::   2) clean        Remove any temporary files generated by the compiler
:: Usage: build.bat <target>
:: Example: build.bat default

@ECHO OFF

:: Only 2 arguments expected
if not "%3"=="" goto usage

set "TARGET=default"
if not "%1"=="" set "TARGET=%1"

set "DEVICE=Arria10"
if not "%2"=="" set "DEVICE=%2"

if "%TARGET%" == "default" (
  echo i++ -march=%DEVICE% 1_ptr_swap_mem.cpp -o 1_ptr_swap_mem.exe
  i++ -march=%DEVICE% 1_ptr_swap_mem.cpp -o 1_ptr_swap_mem.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo i++ -march=%DEVICE% 3_deep_cpy_reg.cpp -o 3_deep_cpy_reg.exe
  i++ -march=%DEVICE% 3_deep_cpy_reg.cpp -o 3_deep_cpy_reg.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo 1_ptr_swap_mem.exe
  1_ptr_swap_mem.exe
  echo 3_deep_cpy_reg.exe
  3_deep_cpy_reg.exe

  echo Compilation complete.  Open the README and the report files to examine the impact of using pointer swap as opposed to deep copy.
  goto:eof

) else if "%TARGET%" == "clean" (
  del /s /f *.tmp
  del /s /f *.exe
  del /s /f *.obj
  rmdir /s /q 1_ptr_swap_mem.prj 2>nul
  rmdir /s /q 3_deep_cpy_reg.prj 2>nul
  goto:eof
) else (
  goto usage
)

:: Dump the usage if we get unexpected input
:usage
echo Usage: build.bat [target]
echo Targets: default, clean
echo Example: build.bat default
exit /b 2
